apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chat-platform
resources:
  - namespace.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - chat-service/deployment.yaml
  - chat-service/service.yaml
  - chat-service/hpa.yaml
  - presence-service/deployment.yaml
  - presence-service/service.yaml
  - notification-service/deployment.yaml
  - notification-service/service.yaml
  - monitoring-service/deployment.yaml
  - monitoring-service/service.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml
  - web/deployment.yaml
  - web/service.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - ingress.yaml
